### ISSUE TITLE
To-do list for staff promotions/demotions/name changes

### ISSUE THREAD

**Issue by ProjectEdenBot** [ProjectEdenGG/Issues#33]
Every time someone joins or leaves the staff team, I have a *lot* of configuration to do. I had a list at one point, but half the items on that list  don't exist any more and it doesn't have a lot of the new things. so here's the new one.

Promotions:
- [ ] LuckPerms promote
- [ ] Discord roles
    - [ ] Make sure they've linked their discord account
- [ ] Make them sign up on the beta site
- [ ] Set tags on [Enjin](http://bear-nation.enjin.com/admin/users)
- [ ] Get their email for mod apps form
- [ ] GitHub alias and collaborators 
    - [ ] Get them to make a github account (
         - Please make a https://github.com/ account and send me the link to your profile (https://github.com/<your username\>)
    - [ ] Add them to the aliases file
        - `~/Jayce/Jayce/aliases.txt`
    - [ ] Add them to collaborators ([BearNation](https://github.com/Pugabyte/BearNation/settings/collaboration) | [Server](https://github.com/Pugabyte/Server/settings/collaboration))
    - [ ] Make them read the [github wiki](https://github.com/PugaBear/BearNation/wiki)
- [ ] Add to birthdays config
- [ ] Set up their staffhall NPC and text 
    - [ ] `/staffhall edit <player> <rank|join|promotion> <text>`
    - [ ] `/staffhall edit <your full ign> <name|about> <text>`
- [ ] Edit [wiki ranks page](https://wiki.bnn.gg/wiki/Ranks#Moderator)
- [ ] Hall of History

Demotions: 
- [ ] Remove from staff array (bottom of staffcommands)
- [ ] Remove from customtext file
- [ ] Remove from birthdays config
- [ ] `/reloadstaffstuff`
- [ ] Set to Veteran in PEX
- [ ] Give Veteran role on Discord 
- [ ] Veteran tag on [Enjin](http://bear-nation.net/admin/users)
- [ ] GitHub
    - [ ] Remove from aliases file
        - `~/Jayce/Jayce/aliases.txt`
    - [ ] Remove them from collaborators ([BearNation](https://github.com/Pugabyte/BearNation/settings/collaboration) | [ServerFiles](https://github.com/Pugabyte/ServerFiles/settings/collaboration) | [Server](https://github.com/Pugabyte/Server/settings/collaboration))
- [ ] Remove from [wiki ranks page](https://wiki.bnn.gg/wiki/Ranks#Moderator)
- [ ] Remove [Dubtrack](https://www.dubtrack.fm/join/bearnation) role
- [ ] Remove and re-order Staff Hall
- [ ] Hall of History

Name changes:
- [ ] Update NPCs in Spawn, HOH and GL
- [ ] Update wiki

**Comment by GriffinCodes** [comment]
Things for you to do:
**Accounts**
Make a <https://projecteden.gg/> account (I know it will error, I'll fix it after you do)
Make a <https://github.com/> account and send me the link to your profile (<https://github.com/><your username>)
I'll also need your gmail (or any email you use to view Google Docs with) to add you to some of our Google Drive stuff.

**Reading** 
<https://docs.google.com/document/d/13lvyoZuMzS-052jlbIa5CaWhu0m0V2m6-mKwPDPMluc/edit?usp=sharing> (5 years old, outdated but mostly useful info)
<https://github.com/ProjectEdenGG/Issues/wiki>
<https://wiki.projecteden.gg/wiki/Commands#Moderator>
All the discord staff channel topics 

**Ingame commands**
```
/discord link
/preferrednames add <preferred name>
/nerd about <about me>
```
