### ISSUE TITLE
Rebranding todo list

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#512]
All things we need to do, and places where we need to change the information

- [x] announcement
- [x] server IP
- [x] motd
- [x] discord
- [x] disboard
- [x] our website pages
- [x] website posts
- [x] the code
- [x] github
- [x] challonge
- voting sites
  - [x] PMC
  - [x] MCMP
  - [x] MCBIZ
  - [x] MCSL
  - [x] MCSO
  - [x] MCSN
  - [x] TMCS
  - [x] TOPG
- banners  
  - [x] PMC
  - [x] MCMP
  - [x] MCBIZ
  - [x] MCSL
  - [x] MCSO
  - [x] MCSN
  - [x] TMCS
  - [x] ~~TOPG~~ N/A
- [x] holographic displays
- [x] social medias + post on every social media of the rebranding
  - [x] youtube / google
  - [x] instagram
  - [x] reddit
  - [x] twitter

**Comment by Lupinez** [comment]
- [x] Store link still needs changing to the Project Eden name

**Comment by Drakimau** [comment]
- [x] Since I don't believe I saw it on the list the ban appeal form, builder apps, and mod apps need updating as well :)
