### ISSUE TITLE
2021 TODO List

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#513]
Server Related:
- [x] #512
- [x] Player Shops 
- [x] Event Store
- [ ] Reminders
- [x] Wither
- [x] Custom Recipes #479 
- [x] MuteMenu
- [x] #528 
- [x] #415 
- [x] #569 
- [x] #4 
- [x] CommandSpy
- [x] Survival PVP Arena
- [ ] Command Documentation
- [ ] #520 
- [ ] #519 

Quests Related:
- [x] ItemTags
- [x] Mob Heads
- [ ] #510 
  
 Misc:
- [x]  /enchant improvements - tab complete applicable enchants

Eventually:
- [ ] Split Nexus
- [ ] Switch to Bungee

**Comment by WakkaFlocka239** [comment]
Updated version at #833
