### ISSUE TITLE
2022 TODO List

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#833]
- [x] Update to Java 17
- [x] Update to Minecraft 1.19

Improvements:
- [ ] RP Stuff
    - [x] Dye Table
        - [x] Stain
    - [x] Plushies
    - [ ] Dye-ify almost everything
- [x] Costumes
    - [x] Dyeable
- [ ] Scoreboard
    - [ ] orderable
- [x] Nameplates Bugs
- [x] Justice Cleanup
    - [x] Fixing delete messages - https://github.com/ProjectEdenGG/Issues/issues/709
    - [x] Website
- [ ] Better particles menu
- [ ] Fix Minigames
    - [ ] Mob Arena - https://github.com/ProjectEdenGG/Issues/issues/519
    - [x] Thimble
    - [x] Starfox
- [ ] Command Framework Improvements
    - [ ] Rewrite
    - [ ] Tab completable redirects
    - [x] Improve permission annotation
    - [x] Async Tab completion
        - [x] Offline Player tab completion 

Additions:
- [ ] Rewrite LWC
- [ ] Website
    - [ ] Rewrite in java
    - [ ] Applications
        - [ ] Separate channels
    - [ ] Minigame Stats
    - [ ] General Stats - https://github.com/ProjectEdenGG/Issues/issues/192
- [ ] Ambience
- [ ] Quest Update
    - [x] Quest Builder
    - [ ] Portable Horses - https://github.com/ProjectEdenGG/Issues/issues/510
    - [ ] Jobs
    - [ ] Mob Events
    - [ ] Mob Equipment
- [ ] Command Documentation
    - [ ] Add descriptions/usage
- [x] Rewrite all Discord commands to slash commands
- [x] Reminders
    - [x] Figure out long-term auth
- [x] New Spawns
    - [x] Hub
    - [x] Survival
    - [x] Game Lobby - https://github.com/ProjectEdenGG/Issues/issues/520
- [ ] New Gamemodes
    - [ ] Skyblock
    - [ ] Challenges
    - [ ] Anarchy?
- [x] Birthdays discord channel
  
Eventually:
- [ ] Split Nexus
- [ ] Switch to Bungee

**Comment by WakkaFlocka239** [comment]
#876
