### ISSUE TITLE
Blast's TODO List

### ISSUE THREAD

**Issue by Blast-MC** [ProjectEdenGG/Issues#870]
- [ ] Crates
    - [ ] Wither Animations
    - [ ] Weekly Wakka Animations
    - [ ] Mystery Animations
        - [ ] Rewards
             - [ ] Tool skins
             - [ ] Tool effects
             - [ ] Teleport Effects
             - [ ] #23 
    - [ ]  https://github.com/ProjectEdenGG/Issues/issues/704

- [ ] Gem Crafter
    - [ ] https://github.com/ProjectEdenGG/Issues/issues/819
    - [ ] https://github.com/ProjectEdenGG/Issues/issues/826

- [ ]  Rewrite Holograms
Clientsided, custom visibility & content handlers
    - [ ] Holograms
    - [ ] Powerups

- [ ] New Vote Reward System
    - [ ] Vote Party
    - [ ] #235 

- [ ] Boss Fights
    - [ ] Framework
    - [ ] Better Party System
    - [ ] Wither Fight
        - [ ] #859 
        - [ ] #825 
        - [ ] #812 
        - [ ] #743 
    - [ ] Dragon Fight
    - [ ] Warden Fight

**Comment by WakkaFlocka239** [comment]
#876
