### ISSUE TITLE
2023 TODO List

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#876]
Griffin:
- [x] Automatic commands wiki page generation
- [ ] #199 
- [ ] Finish Minigame Mechanics
    - [ ] Multimind
    - [ ] Monster Maze
- [ ] LWC rewrite 
- [x] Player Plushies 
- [ ] Walls of Grace
- [x] Website rewrite 
    - [ ] rewrite in Java
    - [ ] Applications
        - [x] Discord threads 
    - [ ] Minigames Stats
    - [ ] General Stats #192
----
Wakka:
- [ ] Custom Blocks
- [ ] Decoration:
    - [x] Functional (?)
    - [ ] Tickable
- [x] Profiles
- [ ] Random Structures
- [ ] Regen Dungeons
- [ ] #726 
- [ ] #766 
    - [ ] Mob Events
    - [ ] Mob Equipment
- [ ] #730 
- [ ] Friends additions (join messages/alerts, tbd)
- [x] Weekly Wakka 
    - [ ] Zones
    - [ ] NPC Hints
- [ ] Aether Dimension
----
Blast:
- [ ] Crates
    - [ ] Types
        - [x] Minigame
        - [ ] Dragon 
        - [ ] Warden
    - [ ] Animations
        - [ ] Wither
        - [x] Weekly Wakka
        - [ ] Mystery 
        - [x] Minigame
        - [ ] Dragon
        - [ ] Warden
    - [ ] Rewards
        - [ ] Tool skins
        - [ ] Tool Effects
        - [ ] Teleport Effects
        - [ ] #23  
- [ ] Gem Crafter
    - [x] #819  
    - [x] #826 
- [x] Rewrite Holograms
    - [x] Holograms
    - [x] Powerups
- [x] New Vote Reward System
    - [x] Vote Party
    - [ ] #235 
- [ ] Boss Fights
    - [ ] Framework
    - [x] Better Party System
    - [ ] Wither Fight
        - [ ] #859 
        - [ ] #825 
        - [ ] #812 
        - [ ] #743 
        - [ ] ProjectEdenGG/Bugs#287
    - [ ] Warden Fight
    - [ ] Dragon Fight 
----
Unassigned:
- [ ] Minigames Related:
    - [ ] New Minigames
        - [ ] Ice Rally
        - [ ] Elytra Racing
        - [x] Turf Wars
        - [ ] #104 
        - [x] TNT Tag
        - [x] #90 
        - [x] #91 
        - [x] Dropper
    - [ ] Convert Games to Minigames
        - [x] Connect4
        - [ ] Tic-Tac-Toe
    - [ ] Add more design stacks to Pixel Drop
    - [ ] #519 
    
- [ ] Survival Related: 
    - [ ] mcMMO Reset Rewards 
    - [ ] Stats Menu leaderboards
    - [ ] Converting Custom Enchants
    
- [ ] Quests Related:
    - [ ] Quests Framework
    - [ ] Dungeons
    - [ ] Money Bags (make killer money drop physical money to deposit at bank)
    - [ ] Teleport Scrolls
    - [ ] Companions (Pets + Mounts + Portable Horses)
    - [ ] Jobs

- [ ] Misc:
    - [ ] Documentation/Wiki stuff #599 
    - [ ] Particles Menu Improvements
        - [ ] Custom Models
        - [ ] Research ideas
        - [ ] Improvements:
            - [ ] #491  
    - [ ] New Gamemodes
        - [ ] #249 
        - [ ] Challenges
        - [ ] Anarchy / Pure Vanilla?
    - [ ] Social Media (posts/ads)
    - [ ] #35 (custom messages)
    - [x] Scoreboard Improvements
        - [x] Orderable
    - [ ] Fake NPCs
    - [ ] Menu Customization (Look through all menus and see if we can customize them more with models/backgrounds)
